#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WIDTH 2560
#define HEIGHT 1440
#define WORKGROUP_SIZE 32

layout(local_size_x=WORKGROUP_SIZE, local_size_y=WORKGROUP_SIZE, local_size_z=1) in;

layout(binding=0, rgba8) uniform image2D result;

void main()
{
    vec4 color = imageLoad(result, ivec2(gl_GlobalInvocationID.xy));
    if(color.r > 0.99)
        color = vec4(0.0, 1.0, 0.0, 1.0);
    imageStore(result, ivec2(gl_GlobalInvocationID.xy), color);
}
